### PR TITLE
Install missing dependencies (with --preact or --inferno flag) + Yarn support

### PR DESCRIPTION
**Pull request by ntwcklng**
Related: #201

### CODE REVIEW

**Comment by ntwcklng** [comment]
Maybe this PR is also a good place for #204?

**Comment by insin** [comment]
This probably is a good place to do that, then we can have a separate install function which handles choosing between nwb and yarn, and manages the spinner stuff etc, so the caller just has to provide a list of modules to be installed.

**Comment by ntwcklng** [comment]
Okay. 
I noticed that `src/commands/build-react.js` isn't used anywhere. Should we ditch it or make it an alias for build-react-app?

**Comment by insin** [comment]
`build-react` and `serve-react` are used by `src/bin/react.js` - they're named that way because you don't need to set up a react app to use them, just point at an entry module.

**Comment by ntwcklng** [comment]
@insin i see you already created a new install function, so this PR is needless. Is there anything else i can help you with?

**Comment by insin** [comment]
@ntwcklng apologies for digging a big hole under the work you did on this - I needed an install function which could check for resolvable dependencies while implementing `inferno build`, as this was a blocker for being able to bundle a module which exports a component, but it turned out generic enough to use everywhere else.

I'm also almost done rewriting most of `createProject.js` to remove synchronous bits and reduce duplication, as it became a copy and paste mess as I added more project types. 

In places you find synchronous stuff or lots of copy and paste in nwb it usually just me being lazy because I needed it to work now rather than having to deal with figuring things out properly, but I've finally been in the mood to fix it recently due to diving into Preact and Inferno.

Let's see where the dust settles after v0.14.

**Comment by ntwcklng** [comment]
Okay, i will close this PR for now 👍

**Pull request closed without merging**
