### PR TITLE
update react templates to use es6 class as default

### PR DESCRIPTION
**Pull request by viankakrisna**
since 15.5^ warns on createClass, i think it's a good time to update the templates :)

### CODE REVIEW

**Comment by loklaan** [comment]
@viankakrisna Great point!

Looks like the tests also need updated though. Could you fix those up?

**Comment by viankakrisna** [comment]
@loklaan it has something to do with .displayName, isn't this should be handled by babel? or es6 class components don't have this by default in nwb? https://travis-ci.org/insin/nwb/jobs/226561810#L2319-L2325 not really sure how to fix the tests

**Comment by loklaan** [comment]
Affected tests are in `tests/commands/build-test.js`

The tests expect `displayName` to be part of the compiled code. This check isn't relevant for code that was compiled from Classes. They should be removed.

**Comment by loklaan** [comment]
Looks like tests failed because of eslint.

Be sure to run `npm run test` locally to catch stuff like that.

**Comment by viankakrisna** [comment]
lint errors fixed, but i got these errors 
screen shot 2017-05-01 at 3 57 26 pm

I think it's because the ordering of OSX filesystem is different. Should I add a commit to sort the arrays before comparing? or open another PR?

**Comment by insin** [comment]
D'oh, I did this separately when I saw the deprecation warnings while updating dependencies - sorry! 😞

**Pull request closed without merging**
