### PR TITLE
Update to babel 6

### PR DESCRIPTION
**Pull request by geowarin**
This is a WIP for #12.
Currently, there is a bit of duplication on the babel presets used for the different builds, we can definitely do something smarter.

I chose to use the following presets for babel:

* es2015
* react
* stage-2 (mainly for the spread syntax)

### CODE REVIEW

**Comment by geowarin** [comment]
The build is broken with npm 2.
With npm 3 the assertions on the node modules present after an init are broken because of the flat package structure.

**Comment by geowarin** [comment]
I have one test failing and I have no idea why:

```
 1) command: test successfully tests a new web module:
     Uncaught Error: "/private/var/folders/15/vg_b15f51vn42dg58tps9xdh0000gn/T/nwb-test1151126-97005-187xv6u/test-module/tests/index-test.js" is not in the SourceMap.
```

Could not reproduce in real conditions so that's definitely weird.

**Comment by geowarin** [comment]
Looks like a bug because of the long file path...

**Comment by geowarin** [comment]
Ok for some reason, karma + webpack + babel 6 refuses to work inside /tmp/.
I used the user home to generate the temp folders.
Build success :smile:

**Comment by insin** [comment]
What does the use case of setting your own babel stage and enabling loose mode look like with Babel 6? i really liked how simple this was with Babel 5 since all the transforms were included, but I suspect we could support the same configuration UI with more work behind the scenes.

**Comment by geowarin** [comment]
Hi @insin.
You are right, the user config part was totally left out by this PR.
I rebased and modified the getUserConfig function so it works with babel 6.

Essentially, the stage is now a preset and not a babel property so we have to extract it out of the user config. Cool side-effect: selecting a babel stage with nwb becomes simpler than with vanilla babel :smile: 

I amended the tests for them to reflect a real usage with babel 6. 
Tell me what you think.

**Comment by geowarin** [comment]
Please clear the travis cache to make the build pass!

**Comment by cafreeman** [comment]
@geowarin Is this still blocked by the travis cache or is there a larger overriding issue? Just ran into the limitations of babel 5 and came looking for this exact issue

**Comment by geowarin** [comment]
Hi @cafreeman! This PR was a work in progress.
It needs rebasing, I haven't taken care of it for months!
I guess @insin is keeping it around for the future.

**Comment by insin** [comment]
@cafreeman Could you add the issues you're having to #12?

I'm using nwb in projects at work which use vanilla Node.js 4 LTS, which comes with npm2. I don't currently need to upgrade to Babel 6 and I'm not willing to make install time, size and performance unacceptable with npm2 in order to do so.

**Comment by joshwcomeau** [comment]
Just my two cents, but I think babel 5 is a better choice for now. Babel 6 has issues with decorators.

**Comment by cafreeman** [comment]
@insin My issues actually were related to presets, but I ended up figuring out how to tweak the `nwb.config` file to configure babel 5 appropriately and now everything works great.

**Comment by tomchentw** [comment]
I'd love to see `nwb` adapt `babel@6`. Since there are many major packages that only supports `babel@6`, e.g. [babel-plugin-lodash][babel-plugin-lodash], and `babel@6` also provides better interfaces for plugins as well. Let me know if there's anything I can help to make this happen.

[babel-plugin-lodash]: https://github.com/lodash/babel-plugin-lodash

**Comment by insin** [comment]
@tomchentw do you know if anyone has made alternative `babel@6` preset modules which provide presets in an npm2-friendly manner?

I was wondering if it would be feasible to have one module which depends on every single plugin with a bunch of entry points for the different presets, and includes all the plugin module dependencies in its own dependencies so they don't get duplicated underneath it.

If that's now possible, I'd rather have `nwb` make a clean, explicit break from npm2 than offer terrible installation time, size and performance.

**Comment by tomchentw** [comment]
@insin FYI, today's news, you may want to try out `babel@^6.8.0` since it seems to reduce lots of dependencies.

**Comment by insin** [comment]
That looks like good news :)

My approach to avoiding that was potentially going to be creating a new package which depends on all the babel plugins and gives you entry points for using them using Babel 5-style `stage` numbers and also entry points equivalent to using `loose: 'all'`. I may still do this as we need to manage that somewhere anyway.

**Comment by insin** [comment]
On second reading, it seems this bug gave npm3 users the npm2 experience w.r.t. babel-runtime when this particular dependency scenario occurred, so it won't improve things with npm2.

This PR looks like it handles the way I want to use `loose` config for plugins, linking it here for later reference: https://github.com/babel/babel/pull/3331

**Comment by slmgc** [comment]
@insin not sure if update to babel 6 is a great idea ATM because it has an issue with parent constructor calls in IE < 11, check it out: https://phabricator.babeljs.io/T3041

**Comment by insin** [comment]
Thanks for the PR @geowarin, it was really handy when getting started with the Babel 6 work, but there ended up being way more I discovered I wanted to do and it turned into a massive commit in the end.

**Pull request closed without merging**
