### PR TITLE
Install missing dependencies (with --preact or --inferno flag)

### PR DESCRIPTION
**Pull request by ntwcklng**
#201

### CODE REVIEW

**Comment by ntwcklng** [comment]
Added an install-spinner:
build

**Comment by insin** [comment]
Aww yeah, thanks for this and the other PRs you've submitted, trying to get a chunk of time to go through them so we can get these landed.

**Comment by insin** [comment]
One thing I need to add to CONTRIBUTING.md is that significant changes are usually done in the `next` branch and there are a bunch of changes in there around async and spinner management which will conflict here, do you mind resubmitting against that branch?

**Comment by ntwcklng** [comment]
Thanks Jonny, contributing to this project is so much fun, i really love it!

Okay, i will dive right into this

**Comment by ntwcklng** [comment]
#214

**Pull request closed without merging**
